name: mongobox
description: "A new Flutter project."

# Remove this if you plan to publish to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.17.5
  qr_flutter: ^4.1.0
  http: ^1.4.0
  cupertino_icons: ^1.0.8
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.4
  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-Bold.ttf
          weight: 700

  uses-material-design: true