// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTMwHxyQVJb_0l39uMKIqka-pGYszGexw',
    appId: '1:850327601337:web:97b8ca86cfda6b37e89b68',
    messagingSenderId: '850327601337',
    projectId: 'mongobox-79a1f',
    authDomain: 'mongobox-79a1f.firebaseapp.com',
    storageBucket: 'mongobox-79a1f.firebasestorage.app',
    measurementId: 'G-7LV14L81DL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS7wPPXayxgyymfytZckX7MQWb5uMUq4I',
    appId: '1:850327601337:android:74f9de7afc3e9997e89b68',
    messagingSenderId: '850327601337',
    projectId: 'mongobox-79a1f',
    storageBucket: 'mongobox-79a1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2_ZjNUUG0kggzZa5iHlZl3haWlrFqvDw',
    appId: '1:850327601337:ios:4e045273a24e3f15e89b68',
    messagingSenderId: '850327601337',
    projectId: 'mongobox-79a1f',
    storageBucket: 'mongobox-79a1f.firebasestorage.app',
    iosBundleId: 'com.example.mongobox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2_ZjNUUG0kggzZa5iHlZl3haWlrFqvDw',
    appId: '1:850327601337:ios:4e045273a24e3f15e89b68',
    messagingSenderId: '850327601337',
    projectId: 'mongobox-79a1f',
    storageBucket: 'mongobox-79a1f.firebasestorage.app',
    iosBundleId: 'com.example.mongobox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTMwHxyQVJb_0l39uMKIqka-pGYszGexw',
    appId: '1:850327601337:web:14ab79cc7e4dddb6e89b68',
    messagingSenderId: '850327601337',
    projectId: 'mongobox-79a1f',
    authDomain: 'mongobox-79a1f.firebaseapp.com',
    storageBucket: 'mongobox-79a1f.firebasestorage.app',
    measurementId: 'G-HEESTFBG8Z',
  );
}
