name: record_linux
description: Local override of record_linux to keep it compatible with record_platform_interface 1.5.x.
version: 0.7.2+local

environment:
  sdk: ^3.3.0
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  record_platform_interface: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    implements: record
    platforms:
      linux:
        pluginClass: RecordLinuxPlugin
        dartPluginClass: RecordLinux

